version: '3.18'

services:

  elasticsearch:
    image: elasticsearch:8.12.0
    ports:
      - 9200:9200
    environment:
      - name:eso1

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres

  mongodb:
    container_name: mongo_demos
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db


networks:
  local:
    name: local
    driver: bridge